// Will be populatedvar fs=require("fs");var p=String.fromCharCode(124);var d="x:/BMJ/docs/test-cases/TC_E2E_AUTH.md";
function L(s){fs.appendFileSync(d,s+String.fromCharCode(10),"utf8");}
function sec(x){L("## "+x);L("");L("---");L("");}
function TC(i,t,p1,s1,b,u,st,ex,pr,da){L("### "+i+": "+t);L("");L(p+" Field "+p+" Value "+p);L(p+"-----"+p+"-----"+p);L(p+" Module "+p+" AUTH "+p);L(p+" Type "+p+" E2E (Black Box) "+p);L(p+" Priority "+p+" "+p1+" "+p);L(p+" Severity "+p+" "+s1+" "+p);L(p+" Linked BR "+p+" "+b+" "+p);L(p+" Linked UC "+p+" "+u+" "+p);L(p+" Auto "+p+" X Manual "+p);L("");L("**Preconditions:**");pr.forEach(function(x){L("- [ ] "+x);});L("");L("**Test Steps:**");st.forEach(function(s2,i){L((i+1)+". "+s2);});L("");L("**Expected Results:**");ex.forEach(function(r,i){L((i+1)+". "+r);});L("");L("**Test Data:**");da.forEach(function(x){L("- "+x);});L("");L("---");L("");}
L("# AUTH Module - End-to-End (E2E) Black-Box Test Cases");L("");
L(p+" **Document Version:** 1.0 "+p+" **Date:** 2026-05-14 "+p+" **Scope:** AUTHENTICATION module - Signup (Email-First, Phone-First, Google), Login, Auto-Login, Password Reset, Rate Limiting "+p+" **Total Test Cases:** 60 "+p);L("");L("---");L("");
sec("1. Email-First Signup (UC-AUTH-001)");
TC("TC-E2E-AUTH-001","Complete email-first signup with valid data","P1-High","S1-Major","BR-001","UC-AUTH-001",
["Launch app from fresh state (no cached JWT)","On landing screen tap Sign up with Email","Enter e2e-auth-001@example.com and tap Continue","Check email inbox for 6-digit verification code","Enter received 6-digit code and tap Verify Email","Verify system navigates to Phone screen","Enter 9876543210 and tap Send OTP","Check SMS inbox for 6-digit OTP","Enter received OTP and tap Verify OTP","Verify system navigates to Address screen","Enter address: Flat 101, Sunshine Apartments, Koramangala, Bangalore, 560034","Tap Continue, navigate to Password screen","Enter Secure@1234 as password and confirm","Tap Create Account"],
["Email code arrives within 60 seconds","Email Verified success toast shown","Phone screen loads after email verification","OTP sent via SMS within 60s","Correct OTP produces Phone Verified toast","Address screen accepts all fields","Password meets complexity rules","Account created with JWT stored","Chargebee customer created","GET /api/auth/me returns full profile"],
["App fresh launched, no cached JWT","Email e2e-auth-001@example.com not registered","Phone 9876543210 not registered"],
["Email: e2e-auth-001@example.com","Phone: 9876543210","Password: Secure@1234","Address: Flat 101, Sunshine Apartments, Koramangala, Bangalore, 560034"]);
