import json  
import os  
os.chdir("x:/BMJ")  
P=chr(124)  
def T(i,t,p,s,b,u,st,ex,pr,da):  
 f.write("### "+i+": "+t+"\n\n")  
 f.write(P+" Field "+P+" Value "+P+"\n")  
 f.write(P+"-----"+P+"-----"+P+"\n")  
 f.write(P+" Module "+P+" AUTH "+P+"\n")  
 f.write(P+" Type "+P+" E2E (Black Box) "+P+"\n")  
 f.write(P+" Priority "+P+" "+p+" "+P+"\n")  
 f.write(P+" Severity "+P+" "+s+" "+P+"\n")  
 f.write(P+" Linked BR "+P+" "+b+" "+P+"\n")  
 f.write(P+" Linked UC "+P+" "+u+" "+P+"\n")  
 f.write(P+" Auto "+P+" X Manual "+P+"\n\n")  
 f.write("**Preconditions:**\n")  
 for x in pr: f.write("- [ ] "+x+"\n")  
 f.write("\n**Test Steps:**\n")  
 for i2,s in enumerate(st,1): f.write(str(i2)+". "+s+"\n")  
 f.write("\n**Expected Results:**\n")  
 for i2,r in enumerate(ex,1): f.write(str(i2)+". "+r+"\n")  
 f.write("\n**Test Data:**\n")  
 for d in da: f.write("- "+d+"\n")  
 f.write("\n---\n\n")  
