import pathlib
p=pathlib.Path("x:/BMJ/docs/test-cases/TC_E2E_AUTH.md")
P=chr(124)
NL=chr(10)
lines=[]
def w(s): lines.append(s)
def SEC(n):
 w("## "+n);w("");w("---");w("")
def TC(id,t,p1,s1,b,u,steps,exp,pre,data):
 w("### "+id+": "+t);w("")
 w(P+" Field "+P+" Value "+P)
 w(P+"---"+P+"---"+P)
 w(P+" **Module** "+P+" AUTH "+P)
 w(P+" **Type** "+P+" E2E (Black Box) "+P)
 w(P+" **Priority** "+P+" "+p1+" "+P)
 w(P+" **Severity** "+P+" "+s1+" "+P)
 w(P+" **Linked BR** "+P+" "+b+" "+P)
 w(P+" **Linked UC** "+P+" "+u+" "+P)
 w(P+" **Auto** "+P+" X Manual "+P)
 w("");w("**Preconditions:**")
 for p2 in pre: w("- [ ] "+p2)
 w("");w("**Test Steps:**")
 for i,s in enumerate(steps,1): w(str(i)+". "+s)
 w("");w("**Expected Results:**")
 for i,r in enumerate(exp,1): w(str(i)+". "+r)
 w("");w("**Test Data:**")
 for d in data: w("- "+d)
 w("");w("---");w("")
