import json, os
os.chdir("x:/BMJ")
P=chr(124)
def sec(n):
 f.write(chr(35)+chr(35)+" "+n+"\n\n---\n\n")
def tc(i,t,p,s,b,u,st,ex,pr,da):
 f.write("### "+i+": "+t+"\n\n")
 f.write(P+" Field "+P+" Value "+P+"\n")
 f.write(P+"-----"+P+"-----"+P+"\n")
 f.write(P+" Module "+P+" AUTH "+P+"\n")
 f.write(P+" Type "+P+" E2E (Black Box) "+P+"\n")
 f.write(P+" Priority "+P+" "+p+" "+P+"\n")
 f.write(P+" Severity "+P+" "+s+" "+P+"\n")
 f.write(P+" Linked BR "+P+" "+b+" "+P+"\n")
 f.write(P+" Linked UC "+P+" "+u+" "+P+"\n")
 f.write(P+" Auto "+P+" X Manual "+P+"\n\n")
 f.write("**Preconditions:**\n")
 for x in pr: f.write("- [ ] "+x+"\n")
 f.write("\n**Test Steps:**\n")
 for i2,s2 in enumerate(st,1): f.write(str(i2)+". "+s2+"\n")
 f.write("\n**Expected Results:**\n")
 for i2,r2 in enumerate(ex,1): f.write(str(i2)+". "+r2+"\n")
 f.write("\n**Test Data:**\n")
 for d in da: f.write("- "+d+"\n")
 f.write("\n---\n\n")
f=open("docs/test-cases/TC_E2E_AUTH.md","w",encoding="utf-8")
f.write("# AUTH Module - E2E Black-Box Test Cases\n\n")
f.write("\n---\n\n")
sec("1. Email-First Signup (UC-AUTH-001)")