import os
os.chdir("x:/BMJ")
P=chr(124);N=chr(10)
def w(s): f.write(s+N)
def S(n): w("## "+n);w("");w("---");w("")
def T(i,t,p1,s1,b,u,st,ex,pr,da):
 w("### "+i+": "+t);w("")
 w(P+" Field "+P+" Value "+P)
 w(P+"-----"+P+"-----"+P)
 w(P+" Module "+P+" AUTH "+P)
 w(P+" Type "+P+" E2E (Black Box) "+P)
 w(P+" Priority "+P+" "+p1+" "+P)
 w(P+" Severity "+P+" "+s1+" "+P)
 w(P+" Linked BR "+P+" "+b+" "+P)
 w(P+" Linked UC "+P+" "+u+" "+P)
 w(P+" Auto "+P+" X Manual "+P)
 w("");w("**Preconditions:")
 for p2 in pr: w("- [ ] "+p2)
 w("");w("**Test Steps:")
 for i2,s in enumerate(st,1): w(str(i2)+". "+s)
 w("");w("**Expected Results:")
 for i2,r in enumerate(ex,1): w(str(i2)+". "+r)
 w("");w("**Test Data:")
 for d in da: w("- "+d)
 w("");w("---");w("")
f=open("docs/test-cases/TC_E2E_AUTH.md","w",encoding="utf-8")
S("1. Email-First Signup")
